openapi: 3.0.0
info:
  title: Company Management API
  description: |- 
    Описание API
  version: 1.0.0
tags:
  - name: user
    description: Operations about user
  - name: branch
    description: Operations about branch
paths:
  /users:
    get:
      summary: Get list of users
      tags:
        - user
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    role:
                      type: string
                    branch_id:
                      type: integer
        '404':
          description: No users found
    post:
      summary: Create a new user
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                role:
                  type: string
                branch_id:
                  type: integer
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
                  branch_id:
                    type: integer
        '400':
          description: Bad Request (empty name/e-mail)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
  /users/{id}:
    get:
      summary: Get a user by ID
      tags:
        - user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
                  branch_id:
                    type: integer
        '404':
          description: User not found
    put:
      summary: Update a user
      tags:
        - user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                role:
                  type: string
                branch_id:
                  type: integer
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
                  branch_id:
                    type: integer
        '400':
          description: Bad Request (empty name/e-mail)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        '404':
          description: User not found
    delete:
      summary: Delete a user
      tags:
        - user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User deleted
        '404':
          description: User not found
  /branches:
    get:
      summary: Get list of branches
      tags:
        - branch
      responses:
        '200':
          description: A list of branches
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    address:
                      type: string
                    director:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
        '404':
          description: No branches found
    post:
      summary: Create a new branch
      tags:
        - branch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
      responses:
        '201':
          description: Branch created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: string
                  director:
                    nullable: true
                  users:
                    type: array
                    items:
                      type: object
                    nullable: true
        '400':
          description: Bad Request (empty name/adress)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
  /branches/{id}:
    get:
      summary: Get a branch by ID
      tags:
        - branch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single branch
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: string
                  director:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '404':
          description: Branch not found
    put:
      summary: Update a branch
      tags:
        - branch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                address:
                  type: string
                director_id:
                  type: integer
      responses:
        '200':
          description: Branch updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: string
                  director:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        '400':
          description: Bad Request (empty name/adress)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        '404':
          description: Branch not found
    delete:
      summary: Delete a branch
      tags:
        - branch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Branch deleted
        '404':
          description: Branch not found